version: "3.8"

services: 
  third_party_api: 
    build: . 
    container_name: third_party_api
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app 
    environment: 
      - MONGO_HOST=third_party_mongo 
      - MONGO_PORT=27017 
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - RABBITMQ_HOST=rabbitmq 
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME} 
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - FACTURA_COM_API_KEY=${FACTURA_COM_API_KEY}
      - FACTURA_COM_SECRET_KEY=${FACTURA_COM_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    env_file: 
      - .env 
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on: 
      - third_party_mongo 
      - rabbitmq

  third_party_consumer:
    build: .
    container_name: third_party_consumer
    command: sh -c "sleep 10 && python -m shared.infrastructure.messaging.consumer_main"
    volumes:
      - ./app:/app
    environment:
      - MONGO_HOST=third_party_mongo 
      - MONGO_PORT=27017 
      - MONGO_USER=${MONGO_USER} 
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=third_party_db
      - RABBITMQ_HOST=rabbitmq 
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME} 
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - FACTURA_COM_API_KEY=${FACTURA_COM_API_KEY}
      - FACTURA_COM_SECRET_KEY=${FACTURA_COM_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    env_file: 
      - .env 
    depends_on:
      rabbitmq:
        condition: service_healthy
      third_party_mongo: 
        condition: service_started

  third_party_mongo: 
    image: mongo:5
    container_name: third_party_mongo 
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes: 
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "5672:5672"   
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes: 
  mongo_data:
  rabbitmq_data:
