version: "3.8"

services: 
  third_party_api: 
    build: . 
    container_name: third_party_api
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app 
    environment: 
      - MONGO_HOST=third_party_mongo 
      - MONGO_PORT=27017 
      - MONGO_USER=admin 
      - MONGO_PASS=secret123 
    env_file: 
      - .env 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 
    depends_on: 
      - third_party_mongo 

  third_party_mongo: 
    image: mongo:5
    container_name: third_party_mongo 
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    volumes: 
      - mongo_data:/data/db

volumes: 
  mongo_data: